remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: Hyperplan
description: Hyperplan's External API Documentation & Tooling
logo: /assets/img/logo.png
show_downloads: false
